pipeline:
  # restore node_modules from cache
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache/drone/da.systems:/cache

  # production build
  build:
    image: node:lts
    commands:
      - npm install
    when:
      branch: [main]

  # 部署正式环境，香港 HK_FE1_B
  deploy_production:
    image: drillster/drone-rsync
    hosts: [ $HOST_IP ]
    user: root
    secrets: [ rsync_key, host_ip ]
    source: ./
    target: /data/code/da.systems
    script:
      - cd /data/code/da.systems
      - npm run reload_produciton
    when:
      branch: [main]

  # 将 node_modules 同步回缓存
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache/drone/da.systems:/cache

  wechat_success:
    image: lizheming/drone-wechat
    secrets: [plugin_corpid, plugin_corp_secret, plugin_agent_id]
    title: '${DRONE_REPO_NAME} ${DRONE_COMMIT_BRANCH} 构建成功✅'
    message: "分支: ${DRONE_COMMIT_BRANCH} 序列: ${DRONE_BUILD_NUMBER}. 提交人: ${DRONE_COMMIT_AUTHOR}. 查看详情: ${DRONE_BUILD_LINK} "
    to_user: 'jeff'
    to_party: 2 # 前端组
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: 详情
    when:
      status: [ success ]

  wechat_failed:
    image: lizheming/drone-wechat
    secrets: [plugin_corpid, plugin_corp_secret, plugin_agent_id]
    title: '${DRONE_REPO_NAME} ${DRONE_COMMIT_BRANCH} 构建失败‼️'
    message: "分支: ${DRONE_COMMIT_BRANCH} 序列: ${DRONE_BUILD_NUMBER}. 提交人: ${DRONE_COMMIT_AUTHOR}. 查看详情: ${DRONE_BUILD_LINK} "
    to_user: 'jeff'
    to_party: 2 #前端组
    msg_url: ${DRONE_BUILD_LINK}
    btn_txt: 失败详情
    when:
      status: [ failure ]
